export type RootStackParamList = {
  LoginAdm: undefined;
  AdminTabs: undefined;
  FuncionarioTabs: undefined;
  LoginFuncionario: undefined;
  HomeFuncionario: undefined;
  Scanner: undefined;
  RegistroMoto: undefined;
  ResumoCadastro: undefined;
  Configuration: undefined;
  ChangePassword: undefined;
  Warning: undefined;
  // ForgotPassword: undefined;
  FuncionarioConfig: undefined;
  CadastrarFuncionario: undefined;
  MapaPateo: undefined;
  ZonaDestinada: undefined;
  MotosDoFuncionario: undefined;
  MapaPatioFunc: undefined;
};
